### ISSUE TITLE
First gvcfgenotyper trial

### ISSUE THREAD

**Issue by PedroBarbosa** [Illumina/gvcfgenotyper#1]
Hello @jaredo 

As we spoke before, I'm trying to use your tool to merge a set of gvcf files, in a similar way as GATK CombineGVCFs/GenotypeGVCFs does.

I ran strelka in several batches of 75 samples, so strelka2 could keep up with the sample number limitation. Therefore, my gvcf output is something like: `batch1: genome.S1.vcf.gz ... genome.S75.vcf.gz; batch2: genome.S1.vcf.gz ... genome.S75.vcf.gz; etc...`

I'm confused on which files to use because in the README you refer we should look for `find directory/ -name '*genome.vcf.gz'` files. But those files are just symbolic links for the first sample gvcf of each batch:  genome.S1.vcf.gz

Shouldn't I list all gvcf of each batch instead ? `find $PWD -name '*genome.S[0-9]*vcf.gz`

Best,
Pedro

**Comment by jaredo** [comment]
>Shouldn't I list all gvcf of each batch instead ? find $PWD -name '*genome.S[0-9]*vcf.gz

That is correct, the `-l` argument expects a plain text file containing the paths to all the GVCFs you wish to merge.

My example just assumes output from single-sample strelka runs are all in the same directory. I need to improve the documentation.

**Comment by olest** [comment]
Hi Pedro, please feel free to re-open this ticket or to contact us directly if anything else is unclear. Closing this ticket now.
