### ISSUE TITLE
GQ field description

### ISSUE THREAD

**Issue by robinpalvadeau** [Illumina/gvcfgenotyper#10]
Dear dev team,

We have generated a multi-sample from our population of WGS data. We want to apply variant quality control (QC) on our dataset. We are considering filtering on GQ field, which is either PASS or LowGQX or LOWGQXHetSNP. However, we could not find any information about how GQ evaluation is computed.
Can you share with us any white papers or description about GQ field? Moreover do you think it a sufficient variant QC? Would you recommend something else? I add that, prior to variant QC we filter on coverage (DP field).
Note that we only have the genome.vcf files for this population generated from Isaac pipeline.

All the best,

Robin

**Comment by olest** [comment]
Hi Robin, 

small variant QC in a population is an open research problem. Therefore it is difficult to recommend steps that will work well in all situations. 

Having said that, filtering by FORMAT/GQ and FORMAT/DP is usually a good idea. If you are using the Isaac pipeline, then FORMAT/GQ (genotype quality) is a confidence score that the genotype is correctly called (Phred scaled, larger values are better). This document contains some information about strelka2 and its variant scoring: https://github.com/Illumina/strelka/tree/v2.9.x/docs

The PASS, LowGQX and LOWGQXHetSNP flags occur in FORMAT/FT which is the FILTER column copied over from the single sample gVCF. 

If you want to take this further, you could take a look at the gnomAD blog and their variant QC for inspiration: https://macarthurlab.org/2018/10/17/gnomad-v2-1/

Ole

**Comment by robinpalvadeau** [comment]
Hi Ole,

Thanks for your quick reply. Sorry, in my first post, I said that FORMAT/GQ field shows result from filtration (PASS, LowGQX and LOWGQXHetSNP flags) but I made a mistake that you have corrected. However, we noticed something else. In our population vcf some variants do not have the FORMAT/FT and some do:

exmple_var 1 : 

`GT:AD:DP:DPF:GQ:GQX     0/0:12,0:12:0:33:.      0/0:21,0:21:0:48:.`

example_var 2 : 

`GT:AD:DP:DPF:FT:GQ:GQX  1/1:0,19:19:7:PASS:54:28`


For both of them, I checked in some of our genome.vcf files, they have PASS flag in the FILTER column.

Best,

Robin

**Comment by olest** [comment]
That's correct. PASS in the single sample gVCF is translated into "." in the msVCF.

**Comment by olest** [comment]
Looking at your examples again, they are actually two different cases:

example_var 1: hom-ref block (GT=0/0) which are always PASS so FT is not copied into the msVCF

example_var 2: FT is PASS so copied as "." in the msVCF.

**Comment by olest** [comment]
I am closing this ticket now, please let us know if you need any further clarification.
