### ISSUE TITLE
undescribed stopage in large cohort

### ISSUE THREAD

**Issue by mwilkers** [Illumina/gvcfgenotyper#12]
Hello,

Thank you again for this great tool.  This was worked well in large cohorts for me.  In one cohort, there is an unexpected crash, midway through one chromosome.  The message supplied is:

gvcfgenotyper: src/cpp/lib/ggutils.cpp:556: int ggutils::bcf1_allele_swap(bcf_hdr_t*, bcf1_t*, int, int): Assertion `bcf_get_format_values(header,record,"AD",(void**)(&format_ad),&num_ad,1)==record->n_allele' failed.

Inspection of the variants around the last successfully genotyped region, do not suggest irregularities in the samples variants or info/format information.

Is there a way to troubleshoot?  Is there a debug option?

Thank you,
Matt

**Comment by olest** [comment]
Hi Matt, thanks for your interest in gvcfgenotyper! 

This error message suggests that there is an entry in one of the input files that is missing the allelic depths FORMAT/AD for at least one of the alleles.

Note that this version of gvcfgenotyper supports only strelka2 gVCF files.

Ole

**Comment by jaredo** [comment]
Hi @mwilkers 

It looks like you are running a slightly older version of gvcfgenotyper. If you use the master branch, there will be a more informative error message that provides the problematic VCF row.

best,

Jared

**Comment by olest** [comment]
I will close this since there wasn't an update for a while. Please re-open if this problem still occurs.
