### ISSUE TITLE
GLIBCXX 3.4.22 Error when invoking gvcfgenotyper

### ISSUE THREAD

**Issue by omoba123** [Illumina/gvcfgenotyper#13]
Installed the gvcfgenotyper on CentOS 7 but receiving the below error. Looks like it need later version of glibc which is not available on CentOS 7 repository and I can't seem to find one from a reliable source on the internet...

Is there a way to get around this or where can I get libstdc++.so.6.0.22  to install on CentOS 7 

./gvcfgenotyper: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./gvcfgenotyper)
./gvcfgenotyper: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./gvcfgenotyper)
./gvcfgenotyper: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./gvcfgenotyper)

**Comment by olest** [comment]
Hi, thanks for your interest in gvcfgenotyper. Did you upgrade your gcc compiler or are you trying to run a gvcfgenotyper binary that was compiled on a different machine? 
Error messages like the one you are seeing usually occur when there is a mismatch between your gcc version and the libstd your OS defaults to. You can usually fix this by adopting the LD_LIBRARY_PATH, see here: https://stackoverflow.com/questions/44205687/glibcxx-3-4-21-not-found-on-centos-7

**Comment by olest** [comment]
Hi, did not receive an answer for several months. Closing this now, feel free to re-open if this is still a problem.
