### ISSUE TITLE
Assertion error on Strelka2 gVCFs

### ISSUE THREAD

**Issue by kaiedasz** [Illumina/gvcfgenotyper#14]
I got an error while merging gVCF files from Strelka2 by using gvcfgenotyper 2019.02.26_master_2019.02.26.

    gvcfgenotyper: src/cpp/lib/DepthBlock.cpp:41: void DepthBlock::Add(const DepthBlock&): Assertion `db._rid == _rid && db._start == (_end + 1)' failed.

I used Strelka2 2.9.10 with the `--rna` flag for variant calling.
Do you have any ideas what is wrong with the gVCF files?

**Comment by wanpinglee** [comment]
Some error here.

**Comment by ghost** [comment]
Hi everyone! I'm having the same error.
Does anyone solved or fixed this problem?

Strelka version: 2.9.10
Error: 
_gvcfgenotyper: src/cpp/lib/DepthBlock.cpp:41: void DepthBlock::Add(const DepthBlock&): Assertion `db._rid == _rid && db._start == (_end + 1)' failed._

**Comment by olest** [comment]
Hi @kaiedasz, @wanpinglee and @treccanimirko , 

thanks for trying out gVCF genotyper.

Could you confirm that this error only occurs with strelka variant calls from RNA-seq data?

RNA-seq data is not supported by gVCF Genotyper. The reason is that the tool makes some assumption about continuous read coverage across the genome.

If you are feeling adventurous, you could comment out this line

https://github.com/Illumina/gvcfgenotyper/blob/d855f75b5aaa715d765ab93bd09f67133207b7e0/src/cpp/lib/DepthBlock.cpp#L41

recompile and try again. Unfortunately we cannot provide support if this does not solve the problem.

Ole

**Comment by ghost** [comment]
Dear @olest ,

thank you for your answer! 

Actually, I'm having the same problem but on Exome Sequencing data.
I'll surely have a look at the "Depth block" code and I'll try it.

Mirko

**Comment by olest** [comment]
Hi @treccanimirko , ah yes, exome data will probably cause this error as well.

**Comment by samkleeman1** [comment]
Did anyone manage to fix this? I am seeing the same error

**Comment by ghost** [comment]
Hi everybody! 
Actually @olest, I had this problem while combining several (174) variants.vcf.gz file. 

I tried merging genome.vcf.gz output files and I finally had my combined vcf.gz of 174 samples and over 85 million SNPs.

Hope to help you out @samkleeman1 @kaiedasz @wanpinglee

**Comment by samkleeman1** [comment]
Commenting out the code as suggested by @olest worked for me

**Comment by olest** [comment]
As a clarification, the only input supported by gVCF genotyper are whole-genome gVCF files generated by strelka2. 

A gVCF as opposed to a VCF has coverage (read depth) info for every position in the genome. As @treccanimirko writes above, you can recognize a gVCF generated by strelka by its "genome.vcf.gz" suffix.

More info here: https://sites.google.com/site/gvcftools/home/about-gvcf

If you have exome or RNA-seq data, you can try to uncomment the line I suggested above, but you will be on your own and should check the output carefully :-)

Hope this helps.

**Comment by kaiedasz** [comment]
I was not aware RNA-Seq data were not supported by gVCF genotyper.
Thanks @olest @treccanimirko @samkleeman1 for your comments and the possible workaround.
