### ISSUE TITLE
Flag FILTER only with "."

### ISSUE THREAD

**Issue by Talo07** [Illumina/gvcfgenotyper#18]
Hi,
After using gvcfgenotyper on the results of strelka (last version), in the flag filter I find only "." I cannot find for example, the PASS and the other criteria... knowing that in the gvcf of each genome there is this information. How I could have them in the final combined vcf??
Thanks !!

**Comment by olest** [comment]
Hi @Talo07 , we don't set the FILTER column in the multi-sample VCF output. That is why it is always set to missing "."

**Comment by Talo07** [comment]
Thanks @olest  for your reply. We would like to filter based on PASS filter, do you have a suggestion?

**Comment by olest** [comment]
hi @Talo07 , I would recommend using the bcftools plugin fill-tags (https://samtools.github.io/bcftools/howtos/plugin.fill-tags.html) to annotate your multi-sample VCF and then use some of these metrics for filtering. The Inbreeding coefficient, Genotype missingness and read depth are good criteria to filter on.
