### ISSUE TITLE
passing filter (FT) missing from output

### ISSUE THREAD

**Issue by mwilkers** [Illumina/gvcfgenotyper#2]
Thank you for this new tool.  I noticed that passing filter in the original sample gvcf is defined in the header. of the output  However, I do not see this value being populated in the FORMAT tags of the output.   Are there particular options required to have PF calculated?  

Thank  you.

**Comment by olest** [comment]
The current release does not yet write the FORMAT/FT tag. We do, however, have an internal version which implements this. 

We plan to make a new release soon. If you need this feature earlier, I could make a pre-release beta available to you.

You are right, the warnings for ADF,ADR etc don’t have anything to do with FORMAT/FT. Their absence, however, indicates that you are using either gvcf files from an older version of the Illumina variant caller (strelka2) or a different variant caller. 

Hope this helps.

Ole

**Comment by olest** [comment]
Closing this ticket now, feel free to contact us or to re-open if you have additional questions.
