### ISSUE TITLE
Can gvcfgenotypes do merging after filtering " pass" calls from each gVCF? 

### ISSUE THREAD

**Issue by gaom001** [Illumina/gvcfgenotyper#20]
Another question came out:  as descibed in the title. Thanks! 
 

Logging output to gvcfgenotyper.20230217_102146.249083.log
gvcfgenotyper: src/cpp/lib/DepthBlock.cpp:41: void DepthBlock::Add(const DepthBlock&): Assertion `db._rid == _rid && db._start == (_end + 1)' failed.

**Comment by olest** [comment]
Hi @gaom001 , gvcfGenotyper assumes that the gVCF has consecutive entries in the gVCF. We recommend to filter the msVCF output file.
