### ISSUE TITLE
Depth block error 

### ISSUE THREAD

**Issue by eabernathy-avalo** [Illumina/gvcfgenotyper#21]
Hello,
  We are attempting to run gvcfgenotyper on a set of 413 gvcfs. All gvcfs were created in the same preprocessing pipeline and variants were called with Strelka. 

The command we are running is:
/gvcfgenotyper_GG-64/bin/gvcfgenotyper -f GCF_000188115.5_SL3.1_genomic.fna -l gvcfs-input.txt -Ob -o combined_vcf.bcf

and the error we are receiving is:
gvcfgenotyper: src/cpp/lib/DepthBlock.cpp:14: DepthBlock::DepthBlock(int, int, int, int, int, int, int): Assertion `end >= 0 && start >= 0' failed.

This error is particularly confusing because it does not give any information as to where the error has occurred, although it did not happen until the program had been running for well over 24 hours.

We appreciated any and all help in trying to get this error resolved. 

Thank you,
 Emily

**Comment by olest** [comment]
Hi @eabernathy-avalo , my apologies for not responding earlier. Were you able to solve this problem?

This error message usually occurs if the gVCF files does not contain information about all the reference positions, meaning there are gaps between entries in the file.
