### ISSUE TITLE
Failing to merge Illumina genome.vcf's

### ISSUE THREAD

**Issue by mmoisse** [Illumina/gvcfgenotyper#6]
I tried to use gvcfgenotyper instead of agg to merge my Illumina genome vcf files. But unlike with agg I fail to merge them probably due to missing files in my input file? Should I used the depricated agg tool instead?

    [info] Opened LP6008126-DNA_A01.genome.vcf.gz 1/594
    [warning] WARNING: LP6008126-DNA_A01.genome.vcf.gz has no FORMAT/ADF tag
    [warning] WARNING: LP6008126-DNA_A01.genome.vcf.gz has no FORMAT/ADR tag
    [warning] WARNING: LP6008126-DNA_A01.genome.vcf.gz has no FORMAT/PL tag
    [warning] WARNING: LP6008126-DNA_A01.genome.vcf.gz has no MQ tag
    ...
    [info] Wrote 0 variants
    [info] Done

**Comment by olest** [comment]
Hi, 

these are just warnings. They suggest that your VCF files are from an outdated version of the Illumina variant caller (strelka2). 

gvcfgenotyper *should* work with legacy VCF files. This should not be the reason for the variant merging to fail but it is also not a recommended use case.

The true error message is probably further down in the log file. Could you post a longer excerpt of the log? Maybe we can see where the problem occurs

**Comment by mmoisse** [comment]
It turned out I misspelled ```chr21``` as ```ch21```
But now the merge fails due to the following error

    ERROR: VCF record did not match the reference at sample LP6008128-DNA_A01 chr21:16811547
    Exiting...

When I look up this position in the vcf file, it seems the reference is wrong in there:

    chr21   16811537        .       AAAAAAAAAACTC   A,AA    567     PASS    CIGAR=1M12D,2M11D;RU=AAAAAAAAACTC,AAAAAAAACTC;REFREP=1,1;IDREP=0,0      GT:GQ:GQX:DPI:AD        1/2:607:16:33:1,14,17
    chr21   16811547        .       CC      AAA,CAA 2       SiteConflict;LowGQXHetSNP       SNVSB=0.0;SNVHPOL=19    GT:GQ:GQX:DP:DPF:AD     1/2:3:12:30:3:0,16,14

The vcf tells 'CC' as reference while according to the ref genome and the previous variant it is 'CT'
The variant caller is indeed the outdated starka-2.1.4.2

Is there a way to relax the software to allow for ref mismatches or correct for them?

Thank you

**Comment by olest** [comment]
I see. Yes, this is a known bug in old versions of strelka2. You can use the undocumented command line option "--ignore-non-matching-ref" to ignore it. I would nevertheless recommend updating strelka.

**Comment by olest** [comment]
Hi, I am closing this issue now. Feel free to open another ticket if the problem persists or if you have other questions.
