### ISSUE TITLE
Memory question

### ISSUE THREAD

**Issue by mmoisse** [Illumina/gvcfgenotyper#7]
Is a memory footprint of ~100GiB to be expected when merging 9600 gvcfs?

**Comment by olest** [comment]
Sounds about right. gvcfgenotyper is buffering 5000 lines per input gVCF file. This is not configurable in the current version but we could change this.

I assume you are not splitting by chromosome and merging in parallel?

**Comment by mmoisse** [comment]
I'm splitting by chromosome because I'm not aware that you can run the tool in parallel

**Comment by olest** [comment]
Hi again, 

you are right. At the moment, the only way to run gvcfgenotyper in parallel is to split the input data by chromosome.

Your memory footprint sounds about right. It is determined by several factors, some of it are out of our control such as the size of the vcf index which is loaded into RAM by htslib. In my experience, the bcftools index (extension .csi) is a bit smaller than the tabix index so indexing your input files using bcftools might help.

Another factor is the buffer size that gvcfgenotyper uses to cache entries in the input gVCF files. The default is to buffer a genomic range of 5K. I just pushed a release which allows to set this on the command line which will reduce the RAM footprint at the cost of runtime.

I will close the ticket now but please do re-open this if you have any more questions.

**Comment by jaredo** [comment]
@mmoisse Re-indexing your input GVCFs with `bcftools index` can yield a huge improvement in memory usage. The reason is that some of the older versions of tabix  produced quite large `.tbi` files.

**Comment by mmoisse** [comment]
@jaredo Thank you for the suggestion, I could reduce the memory usage down to 15-17 GiB using ``.csi`` index files from ``bcftools``

**Comment by jaredo** [comment]
👍
